version: '3.8'
services:
  # This service uses the "graph-worker" image you just built
  worker-0:
    image: graph-worker:v1
    container_name: worker-0  # The Leader will use this name to find it
    networks:
      - graph-net

  worker-1:
    image: graph-worker:v1
    container_name: worker-1  # The Leader will use this name to find it
    networks:
      - graph-net

  worker-2:
    image: graph-worker:v1
    container_name: worker-2  # The Leader will use this name to find it
    networks:
      - graph-net

  leader:
    image: graph-leader:v1
    container_name: leader
    depends_on:
      - worker-0           # Tells Docker to start the worker first
      - worker-1
      - worker-2
    environment:
      - WORKER_PORT=9090
      - NUM_WORKERS=3
    networks:
      - graph-net
    volumes:
      - ./data:/data

networks:
  graph-net:                  # The virtual "room" where they talk
    driver: bridge