version: '3.8'
services:
  # This service uses the "graph-worker" image you just built
  worker-0:
    image: graph-worker:v1
    container_name: worker-0
    hostname: worker-0
    depends_on:
      - leader
    networks:
      - graph-net

  worker-1:
    image: graph-worker:v1
    container_name: worker-1
    hostname: worker-1
    depends_on:
      - leader
    networks:
      - graph-net

  worker-2:
    image: graph-worker:v1
    container_name: worker-2
    hostname: worker-2
    depends_on:
      - leader
    networks:
      - graph-net

  leader:
    image: graph-leader:v1
    container_name: leader
    environment:
      - WORKER_PORT=9090
      - NUM_WORKERS=3
    networks:
      - graph-net
    volumes:
      - ./data:/data

networks:
  graph-net:                  # The virtual "room" where they talk
    driver: bridge