apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-config
  namespace: graph-dist
data:
  NUM_WORKERS: "3"
  WORKER_PORT: "9090"
  WORKER_SERVICE_NAME: "worker"
  LEADER_SERVICE_NAME: "leader"
  LEADER_PORT: "9090"
  NAMESPACE: "graph-dist"
