apiVersion: batch/v1
kind: Job
metadata:
  name: leader
  namespace: graph-dist
  labels:
    app: graph-leader
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: graph-leader
    spec:
      restartPolicy: OnFailure
      containers:
        - name: leader
          image: graph-leader:v1
          imagePullPolicy: Never  # Use local images (minikube)
          env:
            - name: WORKER_PORT
              value: "9090"
            - name: NUM_WORKERS
              value: "3"
            - name: WORKER_SERVICE_NAME
              value: "worker"  # K8s headless service name
            - name: NAMESPACE
              value: "graph-dist"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
