apiVersion: v1
kind: Service
metadata:
  name: leader
  namespace: graph-dist
  labels:
    app: graph-leader
spec:
  selector:
    app: graph-leader
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
